### ISSUE TITLE
Pegar o nome das pessoas ao inves do @

### ISSUE THREAD

**Issue by rdenadai** [milharal-dev/nemli-nemlerei-bot#17]
Sugestao aqui seria talvez pegar o "nome" dos usuarios ao inves dos handlers (`@`) ... visto q no Discord fica visivel o "nome" e nao os handlers

**Comment by ryukinix** [comment]
Ideia boa, pode facilitar o entendimento! Acho que dá pra fazer um replace no texto tendo o map user → name

**Comment by rdenadai** [comment]
**Conversado com o @flipbit03 ao invés de pegarmos os nomes, vamos criar a ref para os usuários pelos seus handlers `@`.**

**Comment by mattpsvreis** [comment]
> **Conversado com o @flipbit03 ao invés de pegarmos os nomes, vamos criar a ref para os usuários pelos seus handlers `@`.**

Eu veto esse caminho pois vai ser chato para quem ficar recebendo @ toda hora por causa do resumo do bot. O ideal seria só pegar o nome e por o @ da pessoa em parenteses ao lado, tipo:

`Rodolfo | ele/he (rdenedai)`

**Comment by rdenadai** [comment]
@mattpsvreis a PR vai pegar o nome mesmo ... precisamos testar pois, inicialmente o q o @ryukinix testou não veio com os nomes corretamente
