### ISSUE TITLE
Separação de respostas por tópicos.

### ISSUE THREAD

**Issue by luksquaresma** [milharal-dev/nemli-nemlerei-bot#28]
Separar as respostas por tópicos na string de resposta do LM para melhorar a legibilidade.

**Comment by ryukinix** [comment]
A separação seria em mensagens diferentes?

Em qua., 24 de jul. de 2024 16:22, Lucas Quaresma ***@***.***>
escreveu:

**Comment by luksquaresma** [comment]
Sim, usando a estrutura de headers. Acabei de commitar aqui, já vou subir o PR.

**Comment by luksquaresma** [comment]
@ryukinix já implementado em [302c05](https://github.com/milharal-dev/nemli-nemlerei-bot/commit/302c05bec178b91d02ec30dad348257fcf424403), caso queira testar no bot de dev. Acho que meu PR parou no CI, vou tentando resolver.
