### ISSUE TITLE
Verificar porque o Header na resposta não apresenta a quantidade total de mensagens

### ISSUE THREAD

**Issue by rdenadai** [milharal-dev/nemli-nemlerei-bot#29]
Anteriormente, quando o bot retornava a resposta trazia como cabeçalho inicial a quantidade de respostas que havia consultado.
Isso se perdeu em algum momento... 

Verificar para restaurar isso.

ANTES
![image](https://github.com/user-attachments/assets/9c7652c9-f709-45a3-af50-89207cee0d4b)

AGORA
![image](https://github.com/user-attachments/assets/aad620fa-84d5-48a3-9364-4a97448e50e9)

**Comment by mattpsvreis** [comment]
O cabeçalho era uma string feita hard coded, tem que ver se não tirou no seu PR

**Comment by rdenadai** [comment]
> O cabeçalho era uma string feita hard coded, tem que ver se não tirou no seu PR

Não... Eu não mexi nessa parte.
Olhei aqui rapidamente e ela existe ainda ... O PR do @luksquaresma mudou isso mas ela ainda existe hardcoded no código, só não tá sendo apresentada mesmo.
