### ISSUE TITLE
Usar slash commands invés de prefix 

### ISSUE THREAD

**Issue by ryukinix** [milharal-dev/nemli-nemlerei-bot#4]
Esse template tá exemplificando como criar comandos pensando em comandos com prefix, i.e: `.meme` ao invés de usar a nova metodologia dos bots de usar Slash Commands.

Seria interessante já pensar em adicionar exemplar em slash command e remover esses de prefix.

_Originalmente postado por @mattpsvreis em https://github.com/milharal-dev/nemli-nemlerei-bot/pull/1#issuecomment-2245657063_

**Comment by mattpsvreis** [comment]
Resolved by PR https://github.com/milharal-dev/nemli-nemlerei-bot/pull/5
