### ISSUE TITLE
Refactor nemli.commands.summarize:response_to_list function

### ISSUE THREAD

**Issue by ryukinix** [milharal-dev/nemli-nemlerei-bot#40]
Suggestion:
Acho q da para diminuir essa complexidade aqui, pq a única coisa q ta mudando é o `summary[:x]` e `summary[x:]`

Criar duas vars com esses caras e ter um único return no fim com toda o resto do code.

_Originally posted by @rdenadai in https://github.com/milharal-dev/nemli-nemlerei-bot/pull/35#discussion_r1691451737_

**Comment by luksquaresma** [comment]
Adicionando: tamanho limite de mensagem dinâmico para considerar já o header.
- BUG: mudanças de header para além do tamanho padrão (100 char) quebram a separação de msgs.

**Comment by ryukinix** [comment]
Boa ideia

Em qui., 25 de jul. de 2024 23:22, Lucas Quaresma ***@***.***>
escreveu:
