### ISSUE TITLE
Implementar sistema de logging (`Loguru`?)

### ISSUE THREAD

**Issue by flipbit03** [milharal-dev/nemli-nemlerei-bot#54]
Implementar sistema de logging (`Loguru`?)

_Originally posted by @flipbit03 in https://github.com/milharal-dev/nemli-nemlerei-bot/pull/53#discussion_r1702429005_

**Comment by ryukinix** [comment]
Já não é utilizado em algumas partes? É dependência do projeto. Eu lembro
de ter inserido. Só não é largamente utilizado.

Em sex., 2 de ago. de 2024 22:36, Cadu ***@***.***> escreveu:

**Comment by flipbit03** [comment]
Eu to um pouco por fora do projeto, na real. Eu vi uns `print()` no PR do Rodolfo e assumi que não tínhamos

**Comment by rdenadai** [comment]
Isso ai é my bad minha que esqueci do loguru ... Já tá configurado no projeto sim.

**Comment by rdenadai** [comment]
Eu vou ajustar a PR depois pra remover esses prints ... Acho q tem print em outros lugares tb

**Comment by ryukinix** [comment]
Ok

Em sáb., 3 de ago. de 2024 11:27, ⟠ Rodolfo De Nadai <
***@***.***> escreveu:
