### ISSUE TITLE
Prompt Engineering: Múltiplos Prompts

### ISSUE THREAD

**Issue by mattpsvreis** [milharal-dev/nemli-nemlerei-bot#6]
Tem de ser criado a possibilidade do usuário escolher vários tipos de prompts para ter uma gama customizada de resultados para tentar adequar ao máximo possível de casos.

**Comment by rdenadai** [comment]
@mattpsvreis ... não entendi muito bem aqui qual o requirement disso?
Quais tipos de prompts? Alguma ideia inicial?

**Comment by ryukinix** [comment]
O modo mexicano

Em qua., 24 de jul. de 2024 15:03, ⟠ Rodolfo De Nadai <
***@***.***> escreveu:

**Comment by ryukinix** [comment]
https://discord.com/channels/1247560692517568603/1265322434391707790/1265405042618400843

Em qui., 25 de jul. de 2024 01:02, Manoel Vilela ***@***.***>
escreveu:

**Comment by rdenadai** [comment]
Entendi ... Um param extra definindo qual o tipo de resposta.
